sonar.projectKey=cedar-rose-questionnaire-web
sonar.projectName=Cedar Rose Questionnaire Web
sonar.projectVersion=1.0.0

sonar.host.url=http://localhost:9000

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/*.test.ts,\
  **/*.test.tsx,\
  src/main.tsx,\
  src/services/index.ts,\
  src/services/types.ts,\
  src/config/env.ts,\
  src/types/**,\
  src/components/ui/**

sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=\
  **/tests/**,\
  src/main.tsx,\
  src/services/index.ts,\
  src/services/types.ts,\
  src/config/env.ts,\
  src/types/**,\
  src/components/ui/**

sonar.coverage.minimum=85
sonar.newCode.disabled=true
sonar.qualitygate.wait=true
