export const ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  CASE_NOT_FOUND: "CASE_NOT_FOUND",
  INVALID_TRANSITION: "INVALID_TRANSITION",
  EMAIL_TYPO_DETECTED: "EMAIL_TYPO_DETECTED",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  SSRF_BLOCKED: "SSRF_BLOCKED",
} as const;
