/** 15-step questionnaire workflow (validate-order-ID step removed). */
export const WORKFLOW_STEP = {
  ORDER_RECEIVED: 1,
  FETCH_COMPANY_DATA: 2,
  APPLY_TEMPLATE: 3,
  GENERATE_LINK: 4,
  SEND_LINK: 5,
  RECIPIENT_OPENS_LINK: 6,
  AUTHENTICATION: 7,
  BEGIN_QUESTIONNAIRE: 8,
  SAVE_PROGRESS: 9,
  MANDATORY_COMPLETE: 10,
  SUBMIT: 11,
  SUBMISSION_RECEIVED: 12,
  RESEARCHER_REVIEW: 13,
  DATA_MAPPING: 14,
  API_PUSH: 15,
} as const;

export const WORKFLOW_STEP_COUNT = 15;
