import { addDays, subDays } from "date-fns";
import type { DrizzleDB } from "../../config/database.js";
import { cases } from "../schema/cases.js";
import { hashToken } from "../../shared/utils/crypto.js";
import { DEMO_LINK_TOKEN, SEED } from "./ids.js";

export async function seedCases(db: DrizzleDB) {
  const now = new Date();
  const linkExpiry = addDays(now, 7);
  const pastExpiry = subDays(now, 2);
  const linkHash = hashToken(DEMO_LINK_TOKEN);

  const rows = [
    {
      caseId: SEED.cases.sent,
      caseRef: "c-seed-001",
      orderId: "ORD-2026-0001",
      companyId: SEED.companies.acme,
      subjectName: "Acme Trading LLC",
      country: "UAE",
      recipientType: "Supplier",
      status: "SENT",
      analystId: SEED.users.analyst,
      researcherStatus: "Not Applicable",
      templateId: SEED.templates.supplierActive,
      templateVersion: 1,
      linkTokenHash: linkHash,
      linkExpiry,
      linkValidityHours: 48,
      currentStep: 5,
      dateReceived: subDays(now, 1),
      dateDispatched: subDays(now, 1),
      createdAt: subDays(now, 1),
      updatedAt: now,
    },
    {
      caseId: SEED.cases.inProgress,
      caseRef: "c-seed-002",
      orderId: "ORD-2026-0002",
      companyId: SEED.companies.acme,
      subjectName: "Acme Trading LLC — Follow-up",
      country: "UAE",
      recipientType: "Supplier",
      status: "IN PROGRESS",
      completionMandatory: 60,
      completionOptional: 0,
      analystId: SEED.users.analyst,
      researcherStatus: "Not Applicable",
      templateId: SEED.templates.supplierActive,
      templateVersion: 1,
      currentStep: 9,
      lastActivity: subDays(now, 1),
      dateReceived: subDays(now, 3),
      dateDispatched: subDays(now, 3),
      firstOpenedAt: subDays(now, 2),
      createdAt: subDays(now, 3),
      updatedAt: now,
    },
    {
      caseId: SEED.cases.completed,
      caseRef: "c-seed-003",
      orderId: "ORD-2026-0003",
      companyId: SEED.companies.gulf,
      subjectName: "Gulf Supplies WLL",
      country: "Bahrain",
      recipientType: "Supplier",
      status: "COMPLETED",
      completionMandatory: 100,
      completionOptional: 50,
      dateSubmitted: subDays(now, 1),
      analystId: SEED.users.analyst,
      assignedResearcherId: SEED.users.researcher,
      researcherStatus: "Awaiting Review",
      templateId: SEED.templates.supplierActive,
      templateVersion: 1,
      currentStep: 13,
      dateReceived: subDays(now, 7),
      dateDispatched: subDays(now, 7),
      firstOpenedAt: subDays(now, 6),
      lastActivity: subDays(now, 1),
      createdAt: subDays(now, 7),
      updatedAt: now,
    },
    {
      caseId: SEED.cases.missingData,
      caseRef: "c-seed-004",
      orderId: "ORD-2026-0004",
      companyId: SEED.companies.gulf,
      subjectName: "Gulf Supplies WLL — Partial",
      country: "Bahrain",
      recipientType: "Supplier",
      status: "COMPLETED — MISSING DATA",
      completionMandatory: 75,
      completionOptional: 0,
      dateSubmitted: subDays(now, 2),
      analystId: SEED.users.analyst,
      assignedResearcherId: SEED.users.researcher,
      researcherStatus: "Awaiting Review",
      templateId: SEED.templates.supplierActive,
      templateVersion: 1,
      currentStep: 13,
      dateReceived: subDays(now, 8),
      dateDispatched: subDays(now, 8),
      firstOpenedAt: subDays(now, 7),
      createdAt: subDays(now, 8),
      updatedAt: now,
    },
    {
      caseId: SEED.cases.expired,
      caseRef: "c-seed-005",
      orderId: "ORD-2026-0005",
      companyId: SEED.companies.acme,
      subjectName: "Acme Trading LLC — Expired Link",
      country: "UAE",
      recipientType: "Supplier",
      status: "EXPIRED",
      analystId: SEED.users.analyst,
      researcherStatus: "Not Applicable",
      templateId: SEED.templates.supplierActive,
      templateVersion: 1,
      linkExpiry: pastExpiry,
      remindersSent: 3,
      dateReceived: subDays(now, 14),
      dateDispatched: subDays(now, 14),
      createdAt: subDays(now, 14),
      updatedAt: now,
    },
    {
      caseId: SEED.cases.pendingContact,
      caseRef: "c-seed-006",
      orderId: "ORD-2026-0006",
      companyId: SEED.companies.acme,
      subjectName: "Acme Trading — No Email",
      country: "UAE",
      recipientType: "Supplier",
      status: "PENDING CONTACT",
      analystId: SEED.users.analyst,
      researcherStatus: "Not Applicable",
      templateId: SEED.templates.supplierActive,
      templateVersion: 1,
      dateReceived: subDays(now, 2),
      createdAt: subDays(now, 2),
      updatedAt: now,
    },
    {
      caseId: SEED.cases.pendingLinkage,
      caseRef: "c-seed-007",
      orderId: "ORD-2026-0007",
      subjectName: "Unknown Entity Ltd",
      country: "UAE",
      recipientType: "Partner",
      status: "PENDING LINKAGE & CONTACT",
      analystId: SEED.users.analyst,
      researcherStatus: "Not Applicable",
      dateReceived: now,
      createdAt: now,
      updatedAt: now,
    },
  ];

  for (const row of rows) {
    await db
      .insert(cases)
      .values(row)
      .onConflictDoUpdate({
        target: cases.caseRef,
        set: {
          status: row.status,
          completionMandatory: row.completionMandatory ?? 0,
          completionOptional: row.completionOptional ?? 0,
          researcherStatus: row.researcherStatus,
          assignedResearcherId: row.assignedResearcherId,
          linkTokenHash: row.linkTokenHash,
          linkExpiry: row.linkExpiry,
          lastActivity: row.lastActivity,
          dateSubmitted: row.dateSubmitted,
          dateDispatched: row.dateDispatched,
          firstOpenedAt: row.firstOpenedAt,
          updatedAt: now,
        },
      });
  }
}
