ALTER TABLE users
  ADD COLUMN IF NOT EXISTS "Title"          VARCHAR(100),
  ADD COLUMN IF NOT EXISTS "Initials"       VARCHAR(5),
  ADD COLUMN IF NOT EXISTS "TotalReports"   INTEGER,
  ADD COLUMN IF NOT EXISTS "Score"          NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS "LastSubmission" TIMESTAMP;
