ALTER TABLE users
  ADD COLUMN IF NOT EXISTS "NotifyOnSubmission"      BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS "NotifyOnLinkExpiry"      BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS "NotifyOnBlockedDispatch" BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS "NotifyOnRemindersSent"   BOOLEAN NOT NULL DEFAULT TRUE;
