sonar.projectKey=cedar-rose-questionnaire-api
sonar.projectName=Cedar Rose Questionnaire API
sonar.projectVersion=1.0.0

sonar.host.url=http://localhost:9000

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/*.test.ts,\
  src/db/migrations/**,\
  src/db/seeds/**,\
  src/swagger/**

sonar.test.inclusions=**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=\
  **/tests/**,\
  src/main.ts,\
  src/db/migrations/**,\
  src/db/seeds/**,\
  src/swagger/**

sonar.coverage.minimum=85
sonar.qualitygate.wait=true